apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: frontend      # Name of this new VirtualDestination (it is referred to)
  namespace: web-ui
spec:
  hosts:
  - frontend.web-ui-team.solo-io.mesh   # Creates a new multi-cluster mesh hostname
  services:
  - labels:
      app: frontend   # Forwards traffic to services with this label
  ports:
  - number: 80
    protocol: HTTP
    targetPort:
      name: http