apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: frontend
  namespace: web-ui
spec:
  hosts:
    - 'shop.glootest.com'
  virtualGateways:
    - name: cluster1-north-south-gw-443
      namespace: istio-gateways
      cluster: cluster1
  workloadSelectors: []
  http:
    - name: frontend
      labels:
        virtual-destination: frontend
        route_name: frontend
      matchers:
      - uri:
          prefix: /
      - uri:
          prefix: /callback
      - uri:
          prefix: /logout
      forwardTo:
        destinations:
          - ref:
              name: frontend
              namespace: web-ui
            kind: VIRTUAL_DESTINATION
            port:
              number: 80