apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: cluster2-north-south-gw-80
  namespace: istio-gateways
spec:
  listeners:
  - http: {}
    port:
      number: 80
  workloads:
  - selector:
      cluster: cluster2
      labels:
        istio: ingressgateway