apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-3-aoa
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ably77/aoa-mgmt/
    targetRevision: 2.1.x-waves
    path: environment/wave-3/active/
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false